name: mlflow-75445c30a631c6b83f0505e6743a24083e38a0a5
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2021.10.8=h033912b_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - libblas=3.9.0=13_osx64_openblas
  - libcblas=3.9.0=13_osx64_openblas
  - libcxx=12.0.1=habf9029_1
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - liblapack=3.9.0=13_osx64_openblas
  - libopenblas=0.3.18=openmp_h3351f45_0
  - libzlib=1.2.11=h9173be1_1013
  - llvm-openmp=12.0.1=hda6cdc1_1
  - ncurses=6.3=he49afe7_0
  - numpy=1.22.1=py310hfbbbacf_0
  - openssl=3.0.0=h0d85af4_2
  - pandas=1.3.5=py310hdd25497_0
  - pip=21.3.1=pyhd8ed1ab_0
  - python=3.10.2=hea1dfa3_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2021.3=pyhd8ed1ab_0
  - readline=8.1=h05e3726_0
  - scikit-learn=1.0.2=py310h598de7d_0
  - scipy=1.7.3=py310h47774c9_0
  - setuptools=59.8.0=py310h2ec42d9_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h23a322b_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=h5dbffcc_1
  - tzdata=2021e=he74cb21_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=haf1e3a3_1
  - zlib=1.2.11=h9173be1_1013
  - pip:
    - certifi==2021.10.8
    - charset-normalizer==2.0.10
    - click==8.0.3
    - configparser==5.2.0
    - docker-pycreds==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.26
    - idna==3.3
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.0
    - pyyaml==6.0
    - requests==2.27.1
    - sentry-sdk==1.5.4
    - shortuuid==1.0.8
    - smmap==5.0.0
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - urllib3==1.26.8
    - wandb==0.12.9
    - yaspin==2.1.0
prefix: /Users/ivanovitchsilva/opt/anaconda3/envs/mlflow-75445c30a631c6b83f0505e6743a24083e38a0a5
