wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1643559271
    t:
      1:
      - 5
      4: 3.8.12
      5: 0.12.9
      8:
      - 5
