wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1643552068
    t:
      4: 3.9.10
      5: 0.12.9
      8:
      - 5
