name: mlflow-7e4931beca2e26802a5a852a6a09a29eda94d1d9
channels:
  - conda-forge
  - defaults
dependencies:
  - brotlipy=0.7.0=py310he24745e_1003
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2021.10.8=h033912b_0
  - certifi=2021.10.8=py310h2ec42d9_1
  - cffi=1.15.0=py310hcc37b68_0
  - chardet=3.0.4=py_1
  - cryptography=36.0.1=py310ha82f1d4_0
  - idna=2.10=pyh9f0ad1d_0
  - libffi=3.4.2=h0d85af4_5
  - libzlib=1.2.11=h9173be1_1013
  - ncurses=6.3=he49afe7_0
  - openssl=1.1.1l=h0d85af4_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h2ec42d9_4
  - python=3.10.2=h1dd9edd_1_cpython
  - python_abi=3.10=2_cp310
  - readline=8.1=h05e3726_0
  - requests=2.24.0=pyh9f0ad1d_0
  - setuptools=60.5.0=py310h2ec42d9_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h23a322b_0
  - tk=8.6.11=h5dbffcc_1
  - tzdata=2021e=he74cb21_0
  - urllib3=1.25.11=py_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=haf1e3a3_1
  - zlib=1.2.11=h9173be1_1013
  - pip:
    - click==8.0.3
    - configparser==5.2.0
    - docker-pycreds==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.26
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.0
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - sentry-sdk==1.5.4
    - shortuuid==1.0.8
    - smmap==5.0.0
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - wandb==0.12.9
    - yaspin==2.1.0
prefix: /Users/ivanovitchsilva/opt/anaconda3/envs/mlflow-7e4931beca2e26802a5a852a6a09a29eda94d1d9
