name: mlflow-521646bdb8ef773b1f4c4ec0a73df68c0c121729
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.4.1=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asn1crypto=1.4.0=pyh9f0ad1d_0
  - brotlipy=0.7.0=py38h96a0964_1003
  - ca-certificates=2021.10.8=h033912b_0
  - certifi=2021.10.8=py38h50d1736_1
  - cffi=1.15.0=py38h1a44b6c_0
  - charset-normalizer=2.0.10=pyhd8ed1ab_0
  - click=8.0.3=py38h50d1736_1
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - configparser=5.2.0=pyhd8ed1ab_0
  - cryptography=36.0.1=py38h56c4533_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - databricks-cli=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - docker-py=5.0.3=py38h50d1736_2
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - flask=2.0.2=pyhd8ed1ab_0
  - freetype=2.10.4=h4cff582_1
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.26=pyhd8ed1ab_0
  - greenlet=1.1.2=py38ha048514_1
  - gunicorn=20.1.0=py38h50d1736_1
  - idna=3.3=pyhd8ed1ab_0
  - itsdangerous=2.0.1=pyhd8ed1ab_0
  - jbig=2.1=h0d85af4_2003
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h0d85af4_0
  - kiwisolver=1.3.2=py38h12bbefe_1
  - lcms2=2.12=h577c468_0
  - lerc=3.0=he49afe7_0
  - libblas=3.9.0=13_osx64_openblas
  - libcblas=3.9.0=13_osx64_openblas
  - libcxx=12.0.1=habf9029_1
  - libdeflate=1.8=h0d85af4_0
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - liblapack=3.9.0=13_osx64_openblas
  - libopenblas=0.3.18=openmp_h3351f45_0
  - libpng=1.6.37=h7cec526_2
  - libprotobuf=3.19.3=hcf210ce_0
  - libtiff=4.3.0=hd146c10_2
  - libwebp-base=1.2.2=h0d85af4_1
  - libzlib=1.2.11=h9173be1_1013
  - llvm-openmp=12.0.1=hda6cdc1_1
  - lz4-c=1.9.3=he49afe7_1
  - mako=1.1.6=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38h96a0964_1
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py38h1300a51_1
  - ncurses=6.3=he49afe7_0
  - numpy=1.22.1=py38h9d72dae_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1l=h0d85af4_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py38ha53d530_0
  - pillow=8.4.0=py38hee640a0_0
  - pip=21.3.1=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.18.7=pyhd8ed1ab_0
  - protobuf=3.19.3=py38ha048514_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h50d1736_4
  - python=3.8.12=h17280f6_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd8ed1ab_0
  - pyyaml=6.0=py38h96a0964_3
  - querystring_parser=1.2.4=py_0
  - readline=8.1=h05e3726_0
  - requests=2.27.1=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py38h37f3bb3_0
  - scipy=1.7.3=py38hd329d04_0
  - setuptools=59.8.0=py38h50d1736_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlalchemy=1.4.31=py38h96a0964_0
  - sqlite=3.37.0=h23a322b_0
  - sqlparse=0.4.2=pyhd8ed1ab_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tenacity=8.0.1=pyhd8ed1ab_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=h5dbffcc_1
  - tornado=6.1=py38h96a0964_2
  - typing_extensions=4.0.1=pyha770c72_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - websocket-client=1.2.3=pyhd8ed1ab_0
  - werkzeug=2.0.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=haf1e3a3_1
  - yaml=0.2.5=h0d85af4_2
  - zlib=1.2.11=h9173be1_1013
  - zstd=1.5.2=h582d3a0_0
  - pip:
    - antlr4-python3-runtime==4.8
    - mlflow==1.14.1
    - omegaconf==2.1.1
    - pathtools==0.1.2
    - promise==2.3
    - psutil==5.9.0
    - sentry-sdk==1.5.4
    - shortuuid==1.0.8
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - wandb==0.12.9
    - yaspin==2.1.0
prefix: /Users/ivanovitchsilva/opt/anaconda3/envs/mlflow-521646bdb8ef773b1f4c4ec0a73df68c0c121729
